# Generated by Django 3.2.7 on 2022-03-04 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='Documents/%y%m%d/')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 3, 5, 1, 4, 41, 18101))),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
